# Generated by Django 5.0.1 on 2026-02-10 21:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('praticien', 'Praticien'), ('patient', 'Patient')], default='patient', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('table_cible', models.CharField(blank=True, max_length=50)),
                ('cible_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='M', max_length=4)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Praticien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Dr', 'Docteur'), ('Pr', 'Professeur')], default='Dr', max_length=3)),
                ('specialite', models.CharField(max_length=100)),
                ('numero_rpps', models.CharField(blank=True, help_text='Numéro RPPS (optionnel)', max_length=11, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='praticiens/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='praticien_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Praticien',
                'verbose_name_plural': 'Praticiens',
            },
        ),
        migrations.CreateModel(
            name='Indisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(help_text='Ex: Congés, Formation, Urgence', max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='rdv_app.praticien')),
            ],
            options={
                'verbose_name': 'Indisponibilité',
                'verbose_name_plural': 'Indisponibilités',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('motif', models.TextField(help_text='Ex: Consultation générale, Contrôle')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('absence', 'Absence sans préavis')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes internes (praticien/admin)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='rdv_app.patient')),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='rdv_app.praticien')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi_prevue', models.DateTimeField()),
                ('type_rappel', models.CharField(choices=[('24h', '24 heures avant'), ('48h', '48 heures avant')], default='24h', max_length=10)),
                ('envoye', models.BooleanField(default=False)),
                ('date_envoi_effectif', models.DateTimeField(blank=True, null=True)),
                ('rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='rdv_app.rendezvous')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'ordering': ['-date_envoi_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Annulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annulations', to='rdv_app.rendezvous')),
            ],
            options={
                'verbose_name': 'Annulation',
                'verbose_name_plural': 'Annulations',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='HorairePraticien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='rdv_app.praticien')),
            ],
            options={
                'verbose_name': 'Horaire Praticien',
                'verbose_name_plural': 'Horaires Praticiens',
                'unique_together': {('praticien', 'jour_semaine', 'heure_debut')},
            },
        ),
    ]
